# Generated by Django 5.2.4 on 2025-08-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='نام و نام خانوادگی')),
                ('age', models.CharField(max_length=2, verbose_name='سن')),
                ('city', models.CharField(max_length=20, verbose_name='محل سکونت')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('resume', models.TextField(verbose_name='متن درخواست شما')),
            ],
        ),
    ]
