# Generated by Django 5.2.4 on 2025-08-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorrequest',
            options={'verbose_name': 'درخواست نویسندگی', 'verbose_name_plural': 'درخواست های نویسندگی'},
        ),
    ]
