# Generated by Django 5.2.4 on 2025-08-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_alter_authorrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorrequest',
            name='email',
            field=models.EmailField(default=1, max_length=128, verbose_name='ایمیل'),
            preserve_default=False,
        ),
    ]
