# Generated by Django 5.2.4 on 2025-08-02 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_authorrequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorrequest',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 09 شروع شود و 11 رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
