# Generated by Django 5.2.4 on 2025-07-18 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(6, message='نام خود را کامل وارد کنید')], verbose_name='نام و نام خانوادگی')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع پیام')),
                ('message', models.TextField(verbose_name='پیام')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 09 شروع شود و شامل ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='تلفن همراه')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='یک ایمیل معتبر وارد کنید!')], verbose_name='ایمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('response', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خاتمه')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
    ]
