# Generated by Django 5.2.4 on 2025-08-05 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComingSoonForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='یک ایمیل معتبر وارد کنید!')], verbose_name='ایمیل')),
            ],
        ),
    ]
