# Generated by Django 5.2.4 on 2025-08-07 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 09 شروع شود و شامل ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='تلفن همراه')),
            ],
            options={
                'verbose_name': 'تلفن مشتری',
                'verbose_name_plural': 'تلفن مشتری ها',
            },
        ),
        migrations.CreateModel(
            name='ComingSoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='یک ایمیل معتبر وارد کنید!')], verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیل ها',
            },
        ),
    ]
