# Generated by Django 5.2.4 on 2025-08-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComingSoonForm',
            new_name='ComingSoon',
        ),
    ]
