# Generated by Django 5.2.4 on 2025-08-06 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_rename_comingsoonform_comingsoon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 09 شروع شود و شامل ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='تلفن همراه')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comingsoon',
            options={'verbose_name': 'ایمیل', 'verbose_name_plural': 'ایمیل ها'},
        ),
    ]
