# Generated by Django 5.2.4 on 2025-08-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_advertising_alter_comingsoon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'verbose_name': 'تلفن مشتری', 'verbose_name_plural': 'تلفن مشتری ها'},
        ),
    ]
