# Generated by Django 5.2.4 on 2025-07-26 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_alter_article_selected_category_articlecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecomments',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='قبول شده / رد شده'),
        ),
    ]
