# Generated by Django 5.2.4 on 2025-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_articlecomments_created_at_articlecomments_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_active',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(default='DF', max_length=25, verbose_name='وضعیت'),
        ),
    ]
