# Generated by Django 5.2.4 on 2025-08-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_remove_article_is_active_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
