# Generated by Django 5.2.4 on 2025-08-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_article_is_rejected_article_rejected_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_rejected',
        ),
    ]
