# Generated by Django 5.2.4 on 2025-07-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumeuser',
            name='about_user',
            field=models.TextField(default='درباره خودت یه چیزی بنویس که بقیه ببینن!', max_length=1000, verbose_name='درباره کاربر'),
        ),
    ]
