# Generated by Django 5.2.4 on 2025-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_customuser_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_user',
            field=models.TextField(default='شما هیچ توضیحاتی درباره خودتان ننوشتید!', max_length=1000, verbose_name='درباره کاربر'),
        ),
    ]
